name: Listen for Status Change

on:
  projects_v2_item:
    types: [edited]

jobs:
  on-status-change:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event payload
        run: echo "${{ toJson(github.event) }}"
